------------ SQL MINI PROJECT - EMPLOYEE MANAGEMENT SYSTEM -------------

-- TO CREATE DATABASE PROJECT
CREATE DATABASE PROJECT;

--TO USE DATABASE PROJECT
USE PROJECT;

--TO CREATE TABLE EMPLOYEE, DEPARTMENTS, ATTENDENCE
CREATE TABLE EMP(
EMP_ID INT PRIMARY KEY,
NAME VARCHAR(50),
DEPT_ID INT ,
SALARY INT,
JOIN_DATE DATE,
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID)
);


CREATE TABLE DEPARTMENTS(
DEPT_ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(50)
);

CREATE TABLE ATTENDANCE(
EMP_ID INT,
DAT DATE,
STATUS VARCHAR(50)
);

INSERT INTO Departments VALUES
(1, 'HR'),
(2, 'IT'),
(3, 'Sales'),
(4, 'Finance');

INSERT INTO Emp VALUES
(101, 'Amit', 2, 60000, '2023-01-15'),
(102, 'Neha', 1, 40000, '2022-11-10'),
(103, 'Raj', 3, 50000, '2023-03-05'),
(104, 'Sneha', 2, 70000, '2021-07-20'),
(105, 'Arjun', 4, 55000, '2022-09-18'),
(106, 'Priya', 3, 45000, '2023-06-12');

INSERT INTO Attendance VALUES
(101, '2024-04-01', 'Present'),
(101, '2024-04-02', 'Absent'),
(102, '2024-04-01', 'Present'),
(103, '2024-04-01', 'Absent'),
(103, '2024-04-02', 'Absent'),
(104, '2024-04-01', 'Present'),
(105, '2024-04-01', 'Absent'),
(106, '2024-04-01', 'Present'),
(106, '2024-04-02', 'Present');

--WRITE QUERISE

--All Employees
SELECT * FROM EMP;

-- List employees with their department names (JOIN)
SELECT E.NAME, D.DEPT_NAME 
FROM EMP AS E
INNER JOIN DEPARTMENTS AS D
ON E.DEPT_ID = D.DEPT_ID;

--Find highest salary in each department
SELECT DEPT_ID, MAX(SALARY) AS MAX_SALARY
FROM EMP 
GROUP BY DEPT_ID;

--Find employees who joined in last 6 months
SELECT * FROM EMP 
WHERE JOIN_DATE >=
DATEADD(MONTH, -6, GETDATE());

--Calculate average salary per department
SELECT DEPT_ID,  AVG(SALARY) 
FROM EMP
GROUP BY DEPT_ID;

--Find employees absent more than 3 days
SELECT EMP_ID, COUNT(*) AS TOTAL_COUNT
FROM ATTENDANCE
GROUP BY EMP_ID
HAVING COUNT(*) > 3;

--employees earning more than avg salary
SELECT NAME, SALARY FROM EMP
WHERE SALARY > (SELECT AVG(SALARY) FROM EMP );

--count absence per employee
SELECT EMP_ID, COUNT(*) AS ABSENT_DAYS
FROM ATTENDANCE
WHERE STATUS = 'ABSENT'
GROUP BY EMP_ID;

--Advanced (to stand out):

--Use ROW_NUMBER() to rank salaries
SELECT NAME, SALARY,
ROW_NUMBER() OVER 
(ORDER BY SALARY DESC) AS RANK
FROM EMP;

--Use subqueries (salary > avg salary)
SELECT NAME, SALARY 
FROM EMP
WHERE SALARY > (SELECT AVG(SALARY) FROM EMP);

--Create a VIEW for reports
CREATE VIEW EMPLOYEE_REPORT AS
SELECT NAME, SALARY, ROW_NUMBER()
OVER
(ORDER BY SALARY DESC) AS RANK
FROM EMP;

SELECT * FROM EMPLOYEE_REPORT;

